# Generated by Django 4.2.29 on 2026-03-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0012_categoria_publicacaopage_categoria_principal'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='categoria_destaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conteudo.categoria', verbose_name='Categoria em destaque'),
        ),
    ]
