# Generated by Django 4.2.29 on 2026-04-10 17:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0044_alter_configuracaosite_modo_manutencao_mensagem'),
        ('home', '0003_homepage_categoria_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mostrar_carrossel_home',
            field=models.BooleanField(default=True, verbose_name='Mostrar carrossel na home'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mostrar_destaques_home',
            field=models.BooleanField(default=True, verbose_name='Mostrar destaques na home'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mostrar_ultimas_publicacoes_home',
            field=models.BooleanField(default=True, verbose_name='Mostrar ultimas publicacoes na home'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ordem_secoes_home',
            field=models.CharField(choices=[('destaques_primeiro', 'Destaques primeiro'), ('ultimas_primeiro', 'Ultimas publicacoes primeiro'), ('intercalado', 'Intercalado')], default='destaques_primeiro', max_length=30, verbose_name='Ordem entre destaques e ultimas publicacoes'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quantidade_itens_carrossel_home',
            field=models.PositiveIntegerField(default=3, verbose_name='Quantidade de itens do carrossel'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quantidade_ultimas_publicacoes_home',
            field=models.PositiveIntegerField(default=5, verbose_name='Quantidade de ultimas publicacoes'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titulo_carrossel_home',
            field=models.CharField(blank=True, default='Publicacoes em destaque', max_length=255, verbose_name='Titulo do carrossel'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titulo_destaques_home',
            field=models.CharField(blank=True, default='Destaques', max_length=255, verbose_name='Titulo da secao de destaques'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titulo_ultimas_publicacoes_home',
            field=models.CharField(blank=True, default='Ultimas publicacoes', max_length=255, verbose_name='Titulo da secao de ultimas publicacoes'),
        ),
        migrations.CreateModel(
            name='HomePageDestaqueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_destaque_home', to='home.homepage')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conteudo.publicacaopage', verbose_name='Publicacao')),
            ],
            options={
                'verbose_name': 'Item de destaque da home',
                'verbose_name_plural': 'Itens de destaque da home',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageCarrosselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_carrossel_home', to='home.homepage')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conteudo.publicacaopage', verbose_name='Publicacao')),
            ],
            options={
                'verbose_name': 'Item do carrossel da home',
                'verbose_name_plural': 'Itens do carrossel da home',
                'ordering': ['sort_order'],
            },
        ),
    ]
