# Generated by Django 4.2.29 on 2026-04-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('home', '0004_homepage_mostrar_carrossel_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarrosselitem',
            name='imagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem do carrossel'),
        ),
    ]
