# Generated by Django 4.2.29 on 2026-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagecarrosselitem_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tempo_transicao_carrossel_home',
            field=models.PositiveIntegerField(default=5, verbose_name='Tempo de transicao do carrossel em segundos'),
        ),
    ]
