# Generated by Django 4.2.29 on 2026-04-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_tempo_transicao_carrossel_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='categoria_destaque',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='ordem_secoes_home',
        ),
    ]
