# Generated by Django 5.2.13 on 2026-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_categoria_destaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='itens_por_pagina_ultimas_home',
            field=models.PositiveIntegerField(default=10, verbose_name='Itens por página (últimas publicações)'),
        ),
    ]
