# Generated by Django 5.2.13 on 2026-04-20 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0082_publicacao_metricas_avaliacoes'),
        ('home', '0009_normalizar_titulos_home_com_acentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='mostrar_ultimas_publicacoes_home',
            field=models.BooleanField(default=True, verbose_name='Mostrar últimas publicações na home'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='quantidade_ultimas_publicacoes_home',
            field=models.PositiveIntegerField(default=5, verbose_name='Quantidade de últimas publicações'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='tempo_transicao_carrossel_home',
            field=models.PositiveIntegerField(default=5, verbose_name='Tempo de transição do carrossel em segundos'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='titulo_carrossel_home',
            field=models.CharField(blank=True, default='Publicações em destaque', max_length=255, verbose_name='Título do carrossel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='titulo_destaques_home',
            field=models.CharField(blank=True, default='Destaques', max_length=255, verbose_name='Título da seção de destaques'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='titulo_ultimas_publicacoes_home',
            field=models.CharField(blank=True, default='Últimas publicações', max_length=255, verbose_name='Título da seção de últimas publicações'),
        ),
        migrations.AlterField(
            model_name='homepagecarrosselitem',
            name='publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conteudo.publicacaopage', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='homepagedestaqueitem',
            name='publicacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conteudo.publicacaopage', verbose_name='Publicação'),
        ),
    ]
