# Generated by Django 4.2.29 on 2026-03-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('nome_exibicao', models.CharField(blank=True, max_length=255, verbose_name='Nome de exibição')),
                ('username', models.SlugField(max_length=80, unique=True, verbose_name='Nome de usuário')),
                ('orcid', models.CharField(blank=True, max_length=19, verbose_name='ORCID')),
                ('mini_bio', models.TextField(blank=True, verbose_name='Mini bio')),
                ('lattes_url', models.URLField(blank=True, verbose_name='Link do Lattes')),
                ('email', models.URLField(verbose_name='Link do Lattes')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Link do Lattes')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome_completo'],
            },
        ),
    ]
