# Generated by Django 4.2.29 on 2026-03-16 19:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('conteudo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='instagram_url',
        ),
        migrations.AddField(
            model_name='autor',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.CreateModel(
            name='PublicacaoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('corpo', wagtail.fields.RichTextField(blank=True, verbose_name='Corpo')),
                ('autores', modelcluster.fields.ParentalManyToManyField(blank=True, to='conteudo.autor')),
                ('imagem_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de capa')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
            bases=('wagtailcore.page',),
        ),
    ]
