# Generated by Django 4.2.29 on 2026-03-17 14:47

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0003_publicacaopagetag_publicacaopage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacaopage',
            name='resumo',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Resumo'),
        ),
    ]
