# Generated by Django 4.2.29 on 2026-03-17 16:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0004_alter_publicacaopage_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('autores', models.CharField(blank=True, max_length=500, verbose_name='Autor(es)')),
                ('titulo_obra', models.CharField(max_length=500, verbose_name='Título da obra')),
                ('subtitulo', models.CharField(blank=True, max_length=500, verbose_name='Subtítulo')),
                ('tipo_midia', models.CharField(blank=True, max_length=120, verbose_name='Tipo de mídia')),
                ('editora', models.CharField(blank=True, max_length=255, verbose_name='Editora')),
                ('local_publicacao', models.CharField(blank=True, max_length=255, verbose_name='Local de publicação')),
                ('ano', models.CharField(blank=True, max_length=20, verbose_name='Ano')),
                ('paginas', models.CharField(blank=True, max_length=120, verbose_name='Páginas')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('publicacao', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='conteudo.publicacaopage')),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
            },
        ),
    ]
