# Generated by Django 4.2.29 on 2026-03-17 18:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0005_referenciapublicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaRodapePublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('marcador', models.CharField(blank=True, max_length=20, verbose_name='Marcador')),
                ('conteudo', wagtail.fields.RichTextField(blank=True, verbose_name='Conteúdo')),
                ('publicacao', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_rodape', to='conteudo.publicacaopage')),
            ],
            options={
                'verbose_name': 'Nota de rodapé',
                'verbose_name_plural': 'Notas de rodapé',
            },
        ),
    ]
