# Generated by Django 4.2.29 on 2026-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0007_autor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciapublicacao',
            name='marcador',
            field=models.CharField(blank=True, max_length=20, verbose_name='Marcador'),
        ),
    ]
