# Generated by Django 4.2.29 on 2026-03-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0008_referenciapublicacao_marcador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenciapublicacao',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='referenciapublicacao',
            name='autor1_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do autor 1'),
        ),
        migrations.AddField(
            model_name='referenciapublicacao',
            name='autor1_sobrenome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sobrenome do autor 1'),
        ),
        migrations.AddField(
            model_name='referenciapublicacao',
            name='autor2_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do autor 2'),
        ),
        migrations.AddField(
            model_name='referenciapublicacao',
            name='autor2_sobrenome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sobrenome do autor 2'),
        ),
        migrations.AddField(
            model_name='referenciapublicacao',
            name='autor3_nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do autor 3'),
        ),
        migrations.AddField(
            model_name='referenciapublicacao',
            name='autor3_sobrenome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sobrenome do autor 3'),
        ),
        migrations.AddField(
            model_name='referenciapublicacao',
            name='usar_et_al',
            field=models.BooleanField(default=False, verbose_name='Usar et al.'),
        ),
        migrations.AlterField(
            model_name='referenciapublicacao',
            name='autores',
            field=models.CharField(blank=True, max_length=500, verbose_name='Autores (campo livre / legado)'),
        ),
    ]
