# Generated by Django 4.2.29 on 2026-03-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0009_alter_referenciapublicacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenciapublicacao',
            options={'verbose_name': 'Referência', 'verbose_name_plural': 'Referências'},
        ),
        migrations.RemoveField(
            model_name='referenciapublicacao',
            name='autores',
        ),
    ]
