# Generated by Django 4.2.29 on 2026-03-18 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0010_alter_referenciapublicacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacaopage',
            name='data_publicacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='destaque_home',
            field=models.BooleanField(default=False, verbose_name='Destacar na home'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='ordem_destaque',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem do destaque'),
        ),
    ]
