# Generated by Django 4.2.29 on 2026-03-19 13:50

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0012_categoria_publicacaopage_categoria_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaIncorporadaPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('url', models.URLField(verbose_name='URL do vídeo')),
                ('legenda', models.TextField(blank=True, verbose_name='Legenda')),
                ('publicacao', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias_embed', to='conteudo.publicacaopage')),
            ],
            options={
                'verbose_name': 'Vídeo externo',
                'verbose_name_plural': 'Vídeos externos',
            },
        ),
    ]
