# Generated by Django 4.2.29 on 2026-03-19 15:17

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('conteudo', '0013_midiaincorporadapublicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('legenda', models.TextField(blank=True, verbose_name='Legenda')),
                ('credito', models.CharField(blank=True, max_length=255, verbose_name='Crédito')),
                ('fonte_url', models.URLField(blank=True, verbose_name='URL da fonte')),
                ('exibir_na_pagina', models.BooleanField(default=True, verbose_name='Exibir na página')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagem')),
                ('publicacao', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_publicacao', to='conteudo.publicacaopage')),
            ],
            options={
                'verbose_name': 'Imagem da publicação',
                'verbose_name_plural': 'Imagens da publicação',
            },
        ),
    ]
