# Generated by Django 4.2.29 on 2026-03-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0014_imagempublicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagempublicacao',
            name='credito',
        ),
        migrations.AddField(
            model_name='imagempublicacao',
            name='credito_texto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Texto do crédito'),
        ),
        migrations.AddField(
            model_name='imagempublicacao',
            name='credito_url',
            field=models.URLField(blank=True, verbose_name='URL do crédito'),
        ),
    ]
