# Generated by Django 4.2.29 on 2026-03-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0015_remove_imagempublicacao_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiaincorporadapublicacao',
            name='exibir_no_final',
            field=models.BooleanField(default=True, verbose_name='Exibir na seção final'),
        ),
        migrations.AddField(
            model_name='midiaincorporadapublicacao',
            name='marcador',
            field=models.CharField(blank=True, max_length=20, verbose_name='Marcador'),
        ),
    ]
