# Generated by Django 4.2.29 on 2026-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0016_midiaincorporadapublicacao_exibir_no_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagempublicacao',
            name='marcador',
            field=models.CharField(blank=True, max_length=20, verbose_name='Marcador'),
        ),
    ]
