# Generated by Django 4.2.29 on 2026-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0017_imagempublicacao_marcador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagempublicacao',
            name='exibir_na_pagina',
            field=models.BooleanField(default=True, verbose_name='Exibir na seção final'),
        ),
    ]
