# Generated by Django 4.2.29 on 2026-03-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0018_alter_imagempublicacao_exibir_na_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacaopage',
            name='data_atualizacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de atualização'),
        ),
    ]
