# Generated by Django 4.2.29 on 2026-03-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0019_publicacaopage_data_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiaincorporadapublicacao',
            name='credito_texto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Texto do crédito'),
        ),
        migrations.AddField(
            model_name='midiaincorporadapublicacao',
            name='credito_url',
            field=models.URLField(blank=True, verbose_name='URL do crédito'),
        ),
        migrations.AddField(
            model_name='midiaincorporadapublicacao',
            name='fonte_url',
            field=models.URLField(blank=True, verbose_name='URL da fonte'),
        ),
    ]
