# Generated by Django 4.2.29 on 2026-03-23 13:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0020_midiaincorporadapublicacao_credito_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacaopage',
            name='autores',
        ),
        migrations.CreateModel(
            name='PublicacaoPageAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conteudo.autor', verbose_name='Autor')),
                ('publicacao', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores_publicacao', to='conteudo.publicacaopage')),
            ],
            options={
                'verbose_name': 'Autor da publicação',
                'verbose_name_plural': 'Autores da publicação',
            },
        ),
    ]
