# Generated by Django 4.2.29 on 2026-03-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0021_remove_publicacaopage_autores_publicacaopageautor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacaopageautor',
            options={'ordering': ['sort_order'], 'verbose_name': 'Autor da publicação', 'verbose_name_plural': 'Autores da publicação'},
        ),
    ]
