# Generated by Django 4.2.29 on 2026-03-23 14:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0022_alter_publicacaopageautor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='publicacaopage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='conteudo.PublicacaoPageTag', to='conteudo.TagPublicacao', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='publicacaopagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_publicacoes', to='conteudo.tagpublicacao'),
        ),
    ]
