# Generated by Django 4.2.29 on 2026-03-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('conteudo', '0023_tagpublicacao_alter_publicacaopage_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(blank=True, max_length=255, verbose_name='Nome do site')),
                ('seo_title_padrao', models.CharField(blank=True, max_length=255, verbose_name='Título SEO padrão')),
                ('descricao_padrao', models.TextField(blank=True, verbose_name='Descrição padrão')),
                ('imagem_compartilhamento_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem padrão de compartilhamento')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configurações do site',
            },
        ),
    ]
