# Generated by Django 4.2.29 on 2026-03-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('conteudo', '0024_configuracaosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='imagem_compartilhamento_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem padrão de compartilhhamento'),
        ),
    ]
