# Generated by Django 4.2.29 on 2026-03-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('conteudo', '0025_configuracaosite_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='copyright_texto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Texto de copyright'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail de contato'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='texto_rodape',
            field=models.TextField(blank=True, verbose_name='Texto do rodapé'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='imagem_compartilhamento_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem padrão de compartilhamento'),
        ),
    ]
