# Generated by Django 4.2.29 on 2026-03-26 17:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('conteudo', '0026_configuracaosite_copyright_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaInstitucionalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('resumo', wagtail.fields.RichTextField(blank=True, verbose_name='Resumo')),
                ('corpo', wagtail.fields.RichTextField(blank=True, verbose_name='Conteúdo')),
                ('imagem_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem de capa')),
            ],
            options={
                'verbose_name': 'Página institucional',
                'verbose_name_plural': 'Páginas institucionais',
            },
            bases=('wagtailcore.page',),
        ),
    ]
