# Generated by Django 4.2.29 on 2026-03-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('conteudo', '0027_paginainstitucionalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='pagina_cookies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de Cookies'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='pagina_privacidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de Privacidade e Dados'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='pagina_sobre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página Sobre'),
        ),
    ]
