# Generated by Django 4.2.29 on 2026-03-26 20:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('conteudo', '0028_configuracaosite_pagina_cookies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introducao', wagtail.fields.RichTextField(blank=True, verbose_name='Introdução')),
                ('email_destino', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de destino')),
                ('mensagem_sucesso', models.CharField(default='Mensagem enviada com sucesso.', max_length=255, verbose_name='Mensagem de sucesso')),
            ],
            options={
                'verbose_name': 'Página de contato',
                'verbose_name_plural': 'Páginas de contato',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='conteudo.contatopage', verbose_name='Página de contato')),
            ],
            options={
                'verbose_name': 'Mensagem de contato',
                'verbose_name_plural': 'Mensagens de contato',
                'ordering': ['-criado_em'],
            },
        ),
    ]
