# Generated by Django 4.2.29 on 2026-03-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('conteudo', '0029_contatopage_mensagemcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='pagina_contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de Contato'),
        ),
    ]
