# Generated by Django 4.2.29 on 2026-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0030_configuracaosite_pagina_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscritoNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('consentimento', models.BooleanField(default=True, verbose_name='Consentimento')),
                ('origem', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Inscrito na newsletter',
                'verbose_name_plural': 'Inscritos na newsletter',
                'ordering': ['-criado_em'],
            },
        ),
    ]
