# Generated by Django 4.2.29 on 2026-03-31 13:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('conteudo', '0031_inscritonewsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introducao', wagtail.fields.RichTextField(blank=True, verbose_name='Introdução')),
                ('mensagem_sucesso', models.CharField(default='Inscrição realizada com sucesso.', max_length=255, verbose_name='Mensagem de sucesso')),
            ],
            options={
                'verbose_name': 'Página de newsletter',
                'verbose_name_plural': 'Páginas de newsletter',
            },
            bases=('wagtailcore.page',),
        ),
    ]
