# Generated by Django 4.2.29 on 2026-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0032_newsletterpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscritonewsletter',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em'),
        ),
        migrations.AlterField(
            model_name='inscritonewsletter',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='inscritonewsletter',
            name='consentimento',
            field=models.BooleanField(default=False, verbose_name='Consentimento'),
        ),
        migrations.AlterField(
            model_name='newsletterpage',
            name='mensagem_sucesso',
            field=models.CharField(default='Confira seu e-mail para confirmar a inscrição.', max_length=255, verbose_name='Mensagem de sucesso'),
        ),
    ]
