# Generated by Django 4.2.29 on 2026-04-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('conteudo', '0033_inscritonewsletter_confirmado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='pagina_newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de Newsletter'),
        ),
    ]
