# Generated by Django 4.2.29 on 2026-04-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0034_configuracaosite_pagina_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('tipo', models.CharField(choices=[('inscricao_solicitada', 'Inscrição solicitada'), ('inscricao_confirmada', 'Inscrição confirmada'), ('cancelamento_solicitado', 'Cancelamento solicitado'), ('cancelamento_confirmado', 'Cancelamento confirmado')], max_length=50, verbose_name='Tipo')),
                ('origem', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('detalhes', models.TextField(blank=True, verbose_name='Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='conteudo.inscritonewsletter', verbose_name='Inscrito')),
            ],
            options={
                'verbose_name': 'Evento da newsletter',
                'verbose_name_plural': 'Eventos da newsletter',
                'ordering': ['-criado_em'],
            },
        ),
    ]
