# Generated by Django 4.2.29 on 2026-04-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0035_newsletterevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoPrivacidadeNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('tipo', models.CharField(choices=[('acesso', 'Solicitação de acesso aos dados'), ('exclusao', 'Solicitação de exclusão dos dados')], max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('atendida', 'Atendida'), ('negada', 'Negada')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Solicitação de privacidade da newsletter',
                'verbose_name_plural': 'Solicitações de privacidade da newsletter',
                'ordering': ['-criado_em'],
            },
        ),
    ]
