# Generated by Django 4.2.29 on 2026-04-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0036_solicitacaoprivacidadenewsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoprivacidadenewsletter',
            name='atendida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Atendida em'),
        ),
    ]
