# Generated by Django 4.2.29 on 2026-04-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0037_solicitacaoprivacidadenewsletter_atendida_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterpage',
            name='mensagem_sucesso',
            field=models.CharField(default='Inscricao realizada com sucesso.', max_length=255, verbose_name='Mensagem de sucesso'),
        ),
    ]
