# Generated by Django 4.2.29 on 2026-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0038_alter_newsletterpage_mensagem_sucesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoprivacidadenewsletter',
            name='arquivo_exportacao',
            field=models.FileField(blank=True, null=True, upload_to='privacidade_newsletter/', verbose_name='Arquivo de exportacao'),
        ),
        migrations.AddField(
            model_name='solicitacaoprivacidadenewsletter',
            name='executada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Executada em'),
        ),
    ]
