# Generated by Django 4.2.29 on 2026-04-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0039_solicitacaoprivacidadenewsletter_arquivo_exportacao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoprivacidadenewsletter',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Solicitacao de privacidade da newsletter', 'verbose_name_plural': 'Solicitacoes de privacidade da newsletter'},
        ),
        migrations.AlterField(
            model_name='solicitacaoprivacidadenewsletter',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observacoes'),
        ),
        migrations.AlterField(
            model_name='solicitacaoprivacidadenewsletter',
            name='tipo',
            field=models.CharField(choices=[('acesso', 'Solicitacao de acesso aos dados'), ('exclusao', 'Solicitacao de exclusao dos dados')], max_length=20, verbose_name='Tipo'),
        ),
    ]
