# Generated by Django 4.2.29 on 2026-04-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0040_alter_solicitacaoprivacidadenewsletter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoprivacidadenewsletter',
            name='confirmacao_usuario_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmacao do usuario em'),
        ),
        migrations.AddField(
            model_name='solicitacaoprivacidadenewsletter',
            name='confirmacao_usuario_exclusao',
            field=models.BooleanField(default=False, verbose_name='Confirmacao do usuario para exclusao'),
        ),
    ]
