# Generated by Django 4.2.29 on 2026-04-07 18:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('conteudo', '0041_solicitacaoprivacidadenewsletter_confirmacao_usuario_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexadorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introducao', wagtail.fields.RichTextField(blank=True, verbose_name='Introducao')),
                ('mensagem_sem_resultados', models.CharField(default='Nenhum registro encontrado.', max_length=255, verbose_name='Mensagem sem resultados')),
                ('itens_por_pagina', models.PositiveIntegerField(default=10, verbose_name='Itens por pagina')),
            ],
            options={
                'verbose_name': 'Pagina do indexador',
                'verbose_name_plural': 'Paginas do indexador',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RegistroIndexador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Titulo da obra')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('ano_publicacao', models.CharField(blank=True, max_length=20, verbose_name='Ano de publicacao')),
                ('dados_editoriais', models.TextField(blank=True, verbose_name='Dados editoriais')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('palavras_chave', models.CharField(blank=True, max_length=500, verbose_name='Palavras-chave')),
                ('doi', models.CharField(blank=True, max_length=255, verbose_name='DOI')),
                ('url_acesso', models.URLField(blank=True, verbose_name='Link de acesso ou download')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Registro do indexador',
                'verbose_name_plural': 'Registros do indexador',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='pagina_indexador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Pagina do Indexador'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='palavras_chave',
            field=models.CharField(blank=True, max_length=500, verbose_name='Palavras-chave'),
        ),
        migrations.CreateModel(
            name='RegistroIndexadorAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do autor')),
                ('orcid', models.CharField(blank=True, max_length=19, verbose_name='ORCID')),
                ('registro', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores_registro', to='conteudo.registroindexador')),
            ],
            options={
                'verbose_name': 'Autor do registro',
                'verbose_name_plural': 'Autores do registro',
                'ordering': ['sort_order'],
            },
        ),
    ]
