# Generated by Django 4.2.29 on 2026-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0042_indexadorpage_registroindexador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='modo_manutencao_ativo',
            field=models.BooleanField(default=False, verbose_name='Modo manutencao ativo'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='modo_manutencao_mensagem',
            field=models.TextField(blank=True, default='Estamos realizando uma manutencao no momento. Tente novamente em alguns minutos.', verbose_name='Mensagem da manutencao'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='modo_manutencao_titulo',
            field=models.CharField(default='Site em manutencao', max_length=255, verbose_name='Titulo da manutencao'),
        ),
    ]
