# Generated by Django 4.2.29 on 2026-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0043_configuracaosite_modo_manutencao_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='modo_manutencao_mensagem',
            field=models.TextField(blank=True, default='Estamos realizando uma manutenção no momento. Tente novamente em alguns minutos.', verbose_name='Mensagem da manutencao'),
        ),
    ]
