# Generated by Django 4.2.29 on 2026-04-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0044_alter_configuracaosite_modo_manutencao_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacaopage',
            name='destaque_home',
        ),
        migrations.RemoveField(
            model_name='publicacaopage',
            name='ordem_destaque',
        ),
    ]
