# Generated by Django 4.2.29 on 2026-04-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0045_remove_publicacaopage_destaque_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroindexadorautor',
            name='nome',
            field=models.CharField(max_length=1000, verbose_name='Nome do autor'),
        ),
    ]
