# Generated by Django 4.2.29 on 2026-04-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0046_alter_registroindexadorautor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='rotulo_indexador',
            field=models.CharField(blank=True, default='Indexador', max_length=255, verbose_name='Rotulo do link do indexador'),
        ),
    ]
