# Generated by Codex on 2026-04-14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("conteudo", "0047_configuracaosite_rotulo_indexador"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicacoesIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "introducao",
                    wagtail.fields.RichTextField(
                        blank=True,
                        verbose_name="Introdução",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pasta de publicações",
                "verbose_name_plural": "Pastas de publicações",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="referenciapublicacao",
            name="marcador",
            field=models.CharField(
                blank=True,
                help_text="Use no corpo do texto como [[r:marcador]]. Exemplo: se o marcador for 1, use [[r:1]].",
                max_length=20,
                verbose_name="Marcador",
            ),
        ),
        migrations.AlterField(
            model_name="notarodapepublicacao",
            name="marcador",
            field=models.CharField(
                blank=True,
                help_text="Use no corpo do texto como [[n:marcador]]. Exemplo: se o marcador for 1, use [[n:1]].",
                max_length=20,
                verbose_name="Marcador",
            ),
        ),
        migrations.AlterField(
            model_name="midiaincorporadapublicacao",
            name="marcador",
            field=models.CharField(
                blank=True,
                help_text="Use no corpo do texto como [[v:marcador]]. Exemplo: se o marcador for video1, use [[v:video1]].",
                max_length=20,
                verbose_name="Marcador",
            ),
        ),
        migrations.AlterField(
            model_name="midiaincorporadapublicacao",
            name="url",
            field=models.URLField(
                help_text="Use uma URL incorporável, como YouTube ou Vimeo.",
                verbose_name="URL do vídeo",
            ),
        ),
        migrations.AlterField(
            model_name="midiaincorporadapublicacao",
            name="exibir_no_final",
            field=models.BooleanField(
                default=False,
                help_text="Uso legado. Prefira inserir o vídeo no corpo com o marcador; o final da publicação mostra apenas os créditos.",
                verbose_name="Exibir na seção final",
            ),
        ),
        migrations.AlterField(
            model_name="imagempublicacao",
            name="marcador",
            field=models.CharField(
                blank=True,
                help_text="Use no corpo do texto como [[i:marcador]]. Exemplo: se o marcador for fig1, use [[i:fig1]].",
                max_length=20,
                verbose_name="Marcador",
            ),
        ),
        migrations.AlterField(
            model_name="imagempublicacao",
            name="exibir_na_pagina",
            field=models.BooleanField(
                default=False,
                help_text="Uso legado. Prefira inserir a imagem no corpo com o marcador; o final da publicação mostra apenas os créditos.",
                verbose_name="Exibir na seção final",
            ),
        ),
        migrations.AlterField(
            model_name="publicacaopage",
            name="imagem_capa",
            field=models.ForeignKey(
                blank=True,
                help_text="Use imagem horizontal padronizada. Recomendado: 1200 x 675 px ou maior, proporção 16:9.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagem de capa",
            ),
        ),
    ]
