# Generated by Codex on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0048_publicacoesindexpage_publication_admin_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosite",
            name="google_search_console_verification",
            field=models.CharField(
                blank=True,
                help_text="Conteúdo do meta tag `google-site-verification` (somente o valor).",
                max_length=255,
                verbose_name="Google Search Console verification",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="meta_domain_verification",
            field=models.CharField(
                blank=True,
                help_text="Conteúdo do meta tag `facebook-domain-verification` (somente o valor).",
                max_length=255,
                verbose_name="Meta domain verification",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="google_analytics_id",
            field=models.CharField(
                blank=True,
                help_text="Exemplo: G-XXXXXXXXXX.",
                max_length=32,
                verbose_name="Google Analytics ID",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="google_tag_manager_id",
            field=models.CharField(
                blank=True,
                help_text="Exemplo: GTM-XXXXXXX.",
                max_length=32,
                verbose_name="Google Tag Manager ID",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="meta_pixel_id",
            field=models.CharField(
                blank=True,
                help_text="Exemplo: 1234567890.",
                max_length=32,
                verbose_name="Meta Pixel ID",
            ),
        ),
    ]
