# Generated by Codex on 2026-04-14

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0049_configuracaosite_rastreamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacaopage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="Use apenas etiquetas já cadastradas. Se a etiqueta necessária não aparecer, peça para um administrador cadastrá-la.",
                through="conteudo.PublicacaoPageTag",
                to="conteudo.TagPublicacao",
                verbose_name="Tags",
            ),
        ),
    ]
