# Generated by Django 5.2.7 on 2026-04-14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0050_alter_publicacaopage_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="usuario_admin",
            field=models.OneToOneField(
                blank=True,
                help_text="Opcional. Vincule um usuário administrador a este autor para controle editorial por autor.",
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=models.SET_NULL,
                related_name="autor_vinculado",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário admin vinculado",
            ),
        ),
    ]
