# Generated by Django 5.2.7 on 2026-04-15

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("conteudo", "0051_autor_usuario_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosite",
            name="usar_menu_customizado",
            field=models.BooleanField(
                default=False,
                help_text="Quando ativo, o menu principal passa a usar os grupos e subitens configurados abaixo.",
                verbose_name="Usar menu customizado",
            ),
        ),
        migrations.CreateModel(
            name="MenuPrincipalGrupo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                ("titulo", models.CharField(max_length=120, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("agrupador", "Apenas agrupador"),
                            ("pagina", "Página interna"),
                            ("url", "URL externa"),
                        ],
                        default="agrupador",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("url_externa", models.URLField(blank=True, verbose_name="URL externa")),
                ("abrir_nova_aba", models.BooleanField(default=False, verbose_name="Abrir em nova aba")),
                (
                    "configuracao_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_grupos",
                        to="conteudo.configuracaosite",
                    ),
                ),
                (
                    "pagina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Página interna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo do menu principal",
                "verbose_name_plural": "Grupos do menu principal",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="MenuPrincipalSubitem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("titulo", models.CharField(max_length=120, verbose_name="Título")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("pagina", "Página interna"), ("url", "URL externa")],
                        default="pagina",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("url_externa", models.URLField(blank=True, verbose_name="URL externa")),
                ("abrir_nova_aba", models.BooleanField(default=False, verbose_name="Abrir em nova aba")),
                (
                    "grupo",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subitens",
                        to="conteudo.menuprincipalgrupo",
                    ),
                ),
                (
                    "pagina",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Página interna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subitem do menu principal",
                "verbose_name_plural": "Subitens do menu principal",
                "ordering": ["sort_order"],
            },
        ),
    ]
