# Generated by Django 5.2.7 on 2026-04-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0026_delete_uploadedimage"),
        ("conteudo", "0052_configuracaosite_usar_menu_customizado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosite",
            name="menu_home_exibir",
            field=models.BooleanField(default=True, verbose_name="Exibir item Home no menu"),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="menu_home_imagem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagem/logo da Home no menu",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="menu_home_primeiro_fixo",
            field=models.BooleanField(
                default=True,
                help_text="Desative para ordenar a Home manualmente via Menu principal.",
                verbose_name="Fixar Home sempre no primeiro item",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="menu_home_rotulo",
            field=models.CharField(blank=True, default="Início", max_length=120, verbose_name="Rótulo da Home no menu"),
        ),
        migrations.AddField(
            model_name="menuprincipalgrupo",
            name="atalho",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("categorias", "Categorias"),
                    ("tags", "Tags"),
                    ("autores", "Autores"),
                    ("busca", "Busca"),
                    ("destaques", "Âncora: Destaques"),
                    ("ultimas", "Âncora: Últimas publicações"),
                    ("contato", "Contato"),
                    ("newsletter", "Newsletter"),
                    ("indexador", "Indexador"),
                ],
                max_length=30,
                verbose_name="Atalho do site",
            ),
        ),
        migrations.AddField(
            model_name="menuprincipalsubitem",
            name="atalho",
            field=models.CharField(
                blank=True,
                choices=[
                    ("home", "Home"),
                    ("categorias", "Categorias"),
                    ("tags", "Tags"),
                    ("autores", "Autores"),
                    ("busca", "Busca"),
                    ("destaques", "Âncora: Destaques"),
                    ("ultimas", "Âncora: Últimas publicações"),
                    ("contato", "Contato"),
                    ("newsletter", "Newsletter"),
                    ("indexador", "Indexador"),
                ],
                max_length=30,
                verbose_name="Atalho do site",
            ),
        ),
    ]
