# Generated by Django 5.2.13 on 2026-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0053_menu_principal_atalhos_e_home"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuprincipalgrupo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("agrupador", "Apenas agrupador"),
                    ("pagina", "Página interna"),
                    ("url", "URL externa"),
                    ("atalho", "Atalho do site"),
                ],
                default="agrupador",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="menuprincipalsubitem",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="menuprincipalsubitem",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("pagina", "Página interna"),
                    ("url", "URL externa"),
                    ("atalho", "Atalho do site"),
                ],
                default="pagina",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
