# Generated by Django 5.2.13 on 2026-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0054_ajustar_tipos_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosite",
            name="menu_home_imagem_escala",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1x"), (2, "2x"), (3, "3x"), (4, "4x"), (5, "5x")],
                default=1,
                help_text="Aplica aumento proporcional quando a Home usa imagem/logo no menu.",
                verbose_name="Escala da imagem/logo da Home",
            ),
        ),
    ]
