# Generated by Django 5.2.13 on 2026-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0055_configuracaosite_menu_home_imagem_escala"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosite",
            name="texto_rodape_link",
            field=models.CharField(
                blank=True,
                help_text="Opcional. Use '#' para subir ao topo da página ou uma URL completa.",
                max_length=255,
                verbose_name="Link do texto do rodapé",
            ),
        ),
    ]
