# Generated by Django 5.2.13 on 2026-04-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0056_configuracaosite_texto_rodape_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacaoprivacidadenewsletter",
            name="executar_apos_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Executar após"),
        ),
    ]
