# Generated by Django 5.2.13 on 2026-04-15 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0057_solicitacaoprivacidadenewsletter_executar_apos_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacaoprivacidadenewsletter',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Solicitação de privacidade da newsletter', 'verbose_name_plural': 'Solicitações de privacidade da newsletter'},
        ),
        migrations.AlterField(
            model_name='solicitacaoprivacidadenewsletter',
            name='arquivo_exportacao',
            field=models.FileField(blank=True, null=True, upload_to='privacidade_newsletter/', verbose_name='Arquivo de exportação'),
        ),
        migrations.AlterField(
            model_name='solicitacaoprivacidadenewsletter',
            name='confirmacao_usuario_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmação do usuário em'),
        ),
        migrations.AlterField(
            model_name='solicitacaoprivacidadenewsletter',
            name='confirmacao_usuario_exclusao',
            field=models.BooleanField(default=False, verbose_name='Confirmação do usuário para exclusão'),
        ),
        migrations.AlterField(
            model_name='solicitacaoprivacidadenewsletter',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='solicitacaoprivacidadenewsletter',
            name='tipo',
            field=models.CharField(choices=[('acesso', 'Solicitação de acesso aos dados'), ('exclusao', 'Solicitação de exclusão dos dados')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ConviteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('nome_completo', models.CharField(blank=True, max_length=255, verbose_name='Nome completo')),
                ('username_sugerido', models.SlugField(blank=True, max_length=80, verbose_name='Nome de usuário sugerido')),
                ('tipo_perfil', models.CharField(choices=[('admin', 'Administrador'), ('autor', 'Autor / Escritor')], default='autor', max_length=20, verbose_name='Perfil')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('token', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Token')),
                ('expira_em', models.DateTimeField(verbose_name='Expira em')),
                ('enviado_em', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('aceito_em', models.DateTimeField(blank=True, null=True, verbose_name='Aceito em')),
                ('erro_envio', models.TextField(blank=True, verbose_name='Erro de envio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario_criado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário criado')),
            ],
            options={
                'verbose_name': 'Convite de usuário',
                'verbose_name_plural': 'Convites de usuários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
