# Generated by Django 4.2.29 on 2026-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0058_alter_solicitacaoprivacidadenewsletter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='travar_publicacao_por_orcid',
            field=models.BooleanField(default=True, help_text='Quando ativo, impede alteração dos autores em publicações já vinculadas a ORCID e exige ORCID dos autores para publicar.', verbose_name='Travar autoria por ORCID nas publicações'),
        ),
    ]
