# Generated by Django 5.2.13 on 2026-04-16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0066_templateemailcampanha"),
    ]

    operations = [
        migrations.AddField(
            model_name="disparoemaildestino",
            name="aberto_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Aberto em"),
        ),
        migrations.AddField(
            model_name="disparoemaildestino",
            name="total_aberturas",
            field=models.PositiveIntegerField(default=0, verbose_name="Total de aberturas"),
        ),
        migrations.AddField(
            model_name="disparoemaildestino",
            name="total_cliques",
            field=models.PositiveIntegerField(default=0, verbose_name="Total de cliques"),
        ),
        migrations.AddField(
            model_name="disparoemaildestino",
            name="tracking_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name="Token de rastreio"),
        ),
        migrations.AddField(
            model_name="disparoemaildestino",
            name="ultimo_clique_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Último clique em"),
        ),
    ]
