# Generated by Django 5.2.13 on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0067_disparoemaildestino_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisparoEmailClique",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=2000, verbose_name="URL clicada")),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Criado em")),
                (
                    "destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliques",
                        to="conteudo.disparoemaildestino",
                        verbose_name="Destino",
                    ),
                ),
                (
                    "disparo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliques",
                        to="conteudo.disparoemail",
                        verbose_name="Disparo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clique de disparo de e-mail",
                "verbose_name_plural": "Cliques de disparos de e-mail",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(fields=["disparo", "criado_em"], name="conteudo_di_disparo_c859fa_idx"),
                    models.Index(fields=["destino", "criado_em"], name="conteudo_di_destino_b7dbcb_idx"),
                ],
            },
        ),
    ]
