# Generated by Django 5.2.13 on 2026-04-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0068_disparoemailclique"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="disparoemailclique",
            new_name="conteudo_di_disparo_034639_idx",
            old_name="conteudo_di_disparo_c859fa_idx",
        ),
        migrations.RenameIndex(
            model_name="disparoemailclique",
            new_name="conteudo_di_destino_48664d_idx",
            old_name="conteudo_di_destino_b7dbcb_idx",
        ),
    ]
