# Generated by Django 5.2.13 on 2026-04-16 20:17

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0069_rename_conteudo_di_disparo_c859fa_idx_conteudo_di_disparo_034639_idx_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEstudoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introducao', wagtail.fields.RichTextField(blank=True, verbose_name='Introdução')),
                ('itens_por_sessao', models.PositiveIntegerField(default=20, verbose_name='Perguntas por sessão')),
            ],
            options={
                'verbose_name': 'Página de quiz de estudos',
                'verbose_name_plural': 'Páginas de quiz de estudos',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='pagina_quiz_estudo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Página de quiz de estudos'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='paleta_cor_1',
            field=models.CharField(default='#0f172a', help_text='Hexadecimal no formato #RRGGBB.', max_length=7, verbose_name='Paleta cor 1'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='paleta_cor_2',
            field=models.CharField(default='#1d4ed8', help_text='Hexadecimal no formato #RRGGBB.', max_length=7, verbose_name='Paleta cor 2'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='paleta_cor_3',
            field=models.CharField(default='#f59e0b', help_text='Hexadecimal no formato #RRGGBB.', max_length=7, verbose_name='Paleta cor 3'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='paleta_cor_4',
            field=models.CharField(default='#f8fafc', help_text='Hexadecimal no formato #RRGGBB.', max_length=7, verbose_name='Paleta cor 4'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='rotulo_quiz_estudo',
            field=models.CharField(blank=True, default='Quiz', max_length=255, verbose_name='Rótulo do link de quiz'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='tema_padrao_site',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('claro', 'Claro'), ('escuro', 'Escuro')], default='sistema', max_length=20, verbose_name='Tema padrão do site'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='quiz_habilitado',
            field=models.BooleanField(default=False, verbose_name='Habilitar quiz nesta publicação'),
        ),
        migrations.CreateModel(
            name='QuizPerguntaPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('pergunta', models.CharField(max_length=500, verbose_name='Pergunta')),
                ('explicacao', models.TextField(blank=True, verbose_name='Explicação (opcional)')),
                ('publicacao', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_perguntas', to='conteudo.publicacaopage')),
            ],
            options={
                'verbose_name': 'Pergunta de quiz',
                'verbose_name_plural': 'Perguntas de quiz',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuizOpcaoPerguntaPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('texto', models.CharField(max_length=400, verbose_name='Texto da opção')),
                ('correta', models.BooleanField(default=False, verbose_name='Correta')),
                ('pergunta', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='conteudo.quizperguntapublicacao')),
            ],
            options={
                'verbose_name': 'Opção da pergunta',
                'verbose_name_plural': 'Opções da pergunta',
                'ordering': ['sort_order'],
            },
        ),
    ]
