# Generated by Django 5.2.13 on 2026-04-16 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0070_quizestudopage_configuracaosite_pagina_quiz_estudo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacaopage',
            name='aguardando_aprovacao_admin',
            field=models.BooleanField(default=False, verbose_name='Aguardando aprovação do administrador'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='enviado_aprovacao_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado para aprovação em'),
        ),
    ]
