# Generated by Django 5.2.13 on 2026-04-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0071_publicacaopage_aguardando_aprovacao_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='tema_padrao_site',
            field=models.CharField(choices=[('claro', 'Claro'), ('escuro', 'Escuro')], default='claro', max_length=20, verbose_name='Tema padrão do site'),
        ),
    ]
