# Generated by Django 5.2.13 on 2026-04-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0073_normalizar_tema_padrao_claro_escuro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosite',
            name='paleta_cor_3',
        ),
        migrations.RemoveField(
            model_name='configuracaosite',
            name='paleta_cor_4',
        ),
    ]
