# Generated by Django 5.2.13 on 2026-04-19 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("conteudo", "0074_drop_paleta_3_4"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosite",
            name="menu_home_imagem_claro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagem/logo da Home (tema claro)",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="menu_home_imagem_escuro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Imagem/logo da Home (tema escuro)",
            ),
        ),
    ]
