# Generated by Django 5.2.13 on 2026-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0075_configuracaosite_menu_home_imagem_claro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosite",
            name="idioma_site",
            field=models.CharField(
                choices=[("pt-br", "Português (Brasil)"), ("en", "English")],
                default="pt-br",
                help_text="Define o idioma da interface pública (menu, rótulos e mensagens padrão).",
                max_length=10,
                verbose_name="Idioma do site público",
            ),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="social_facebook_url",
            field=models.URLField(blank=True, verbose_name="Facebook (URL)"),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="social_instagram_url",
            field=models.URLField(blank=True, verbose_name="Instagram (URL)"),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="social_linkedin_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn (URL)"),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="social_x_url",
            field=models.URLField(blank=True, verbose_name="X / Twitter (URL)"),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="social_youtube_url",
            field=models.URLField(blank=True, verbose_name="YouTube (URL)"),
        ),
    ]
