# Generated by Django 5.2.13 on 2026-04-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0076_configuracaosite_idioma_site_and_social_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaosite",
            name="idioma_site",
            field=models.CharField(
                choices=[
                    ("pt-br", "Português (Brasil)"),
                    ("en", "English"),
                    ("es", "Español"),
                ],
                default="pt-br",
                help_text="Define o idioma da interface pública (menu, rótulos e mensagens padrão).",
                max_length=10,
                verbose_name="Idioma do site público",
            ),
        ),
    ]
