# Generated by Django 5.2.13 on 2026-04-20 00:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0077_alter_configuracaosite_idioma_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosite",
            name="comentarios_ativos",
            field=models.BooleanField(default=False, verbose_name="Ativar comentários públicos"),
        ),
        migrations.AddField(
            model_name="configuracaosite",
            name="comentarios_auto_newsletter",
            field=models.BooleanField(
                default=True,
                help_text="Quando ativo, usuários que confirmarem comentário serão inscritos na newsletter e poderão cancelar depois pela página de newsletter.",
                verbose_name="Cadastrar comentaristas na newsletter automaticamente",
            ),
        ),
        migrations.AddField(
            model_name="publicacaopage",
            name="comentarios_habilitados",
            field=models.BooleanField(default=True, verbose_name="Habilitar comentários nesta publicação"),
        ),
        migrations.CreateModel(
            name="UsuarioComentario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="E-mail")),
                ("username", models.SlugField(max_length=80, unique=True, verbose_name="Nome de usuário")),
                ("orcid", models.CharField(blank=True, max_length=19, verbose_name="ORCID")),
                ("verificado_em", models.DateTimeField(auto_now_add=True, verbose_name="Verificado em")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
            ],
            options={
                "verbose_name": "Usuário de comentário",
                "verbose_name_plural": "Usuários de comentário",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioPublicacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texto", models.TextField(verbose_name="Comentário")),
                (
                    "status",
                    models.CharField(
                        choices=[("pendente", "Pendente"), ("aprovado", "Aprovado"), ("rejeitado", "Rejeitado")],
                        db_index=True,
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("sinalizado_conteudo", models.BooleanField(default=False, verbose_name="Sinalizado para moderação reforçada")),
                ("ip_origem", models.GenericIPAddressField(blank=True, null=True, verbose_name="IP de origem")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "publicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios_publicacao",
                        to="conteudo.publicacaopage",
                        verbose_name="Publicação",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="conteudo.usuariocomentario",
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário da publicação",
                "verbose_name_plural": "Comentários das publicações",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioVerificacaoToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Token")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("username", models.SlugField(max_length=80, verbose_name="Nome de usuário")),
                ("orcid", models.CharField(blank=True, max_length=19, verbose_name="ORCID")),
                ("texto", models.TextField(verbose_name="Comentário")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("expira_em", models.DateTimeField(verbose_name="Expira em")),
                ("usado_em", models.DateTimeField(blank=True, null=True, verbose_name="Usado em")),
                (
                    "publicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="conteudo.publicacaopage",
                        verbose_name="Publicação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de verificação de comentário",
                "verbose_name_plural": "Tokens de verificação de comentários",
                "ordering": ["-criado_em"],
            },
        ),
    ]
