# Generated by Django 5.2.13 on 2026-04-19 18:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conteudo", "0078_comentarios_publicos_models_and_fields"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indexadorpage",
            options={"verbose_name": "Página do indexador", "verbose_name_plural": "Páginas do indexador"},
        ),
        migrations.AlterField(
            model_name="configuracaosite",
            name="modo_manutencao_ativo",
            field=models.BooleanField(default=False, verbose_name="Modo manutenção ativo"),
        ),
        migrations.AlterField(
            model_name="configuracaosite",
            name="modo_manutencao_mensagem",
            field=models.TextField(
                blank=True,
                default="Estamos realizando uma manutenção no momento. Tente novamente em alguns minutos.",
                verbose_name="Mensagem da manutenção",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaosite",
            name="modo_manutencao_titulo",
            field=models.CharField(default="Site em manutenção", max_length=255, verbose_name="Título da manutenção"),
        ),
        migrations.AlterField(
            model_name="configuracaosite",
            name="pagina_indexador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Página do Indexador",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaosite",
            name="rotulo_indexador",
            field=models.CharField(blank=True, default="Indexador", max_length=255, verbose_name="Rótulo do link do indexador"),
        ),
        migrations.AlterField(
            model_name="indexadorpage",
            name="introducao",
            field=wagtail.fields.RichTextField(blank=True, verbose_name="Introdução"),
        ),
        migrations.AlterField(
            model_name="indexadorpage",
            name="itens_por_pagina",
            field=models.PositiveIntegerField(default=10, verbose_name="Itens por página"),
        ),
        migrations.AlterField(
            model_name="registroindexador",
            name="ano_publicacao",
            field=models.CharField(blank=True, max_length=20, verbose_name="Ano de publicação"),
        ),
        migrations.AlterField(
            model_name="registroindexador",
            name="titulo",
            field=models.CharField(max_length=500, verbose_name="Título da obra"),
        ),
    ]
