# Generated by Django 5.2.13 on 2026-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0080_merge_0079_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='contatopage',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='indexadorpage',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='newsletterpage',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='paginainstitucionalpage',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='publicacoesindexpage',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='quizestudopage',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='tagpublicacao',
            name='traducoes',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
