# Generated by Django 5.2.13 on 2026-04-24 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0088_remove_configuracaosite_menu_home_imagem_escala'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='menu_home_logo_ajuste',
            field=models.CharField(choices=[('conter', 'Manter proporção da imagem'), ('preencher', 'Redimensionar para preencher a proporção')], default='conter', help_text="Em 'preencher', a imagem ocupa toda a área definida pela proporção escolhida.", max_length=20, verbose_name='Modo de ajuste da imagem'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='menu_home_logo_altura_desktop_px',
            field=models.PositiveSmallIntegerField(default=72, help_text='Altura máxima em pixels para desktop. Intervalo: 24 a 80.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(80)], verbose_name='Altura do botão/logo da Home no desktop (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='menu_home_logo_altura_mobile_px',
            field=models.PositiveSmallIntegerField(default=50, help_text='Altura máxima em pixels para mobile. Intervalo: 24 a 80.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(80)], verbose_name='Altura do botão/logo da Home no mobile (px)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='menu_home_logo_proporcao',
            field=models.CharField(choices=[('auto', 'Manter proporção original da imagem'), ('1:1', '1:1'), ('3:2', '3:2'), ('4:3', '4:3'), ('16:9', '16:9'), ('21:9', '21:9'), ('12:5', '12:5'), ('5:1', '5:1')], default='auto', help_text='Defina uma proporção fixa ou mantenha a original do arquivo enviado.', max_length=20, verbose_name='Proporção do botão/logo da Home'),
        ),
    ]
