# Generated by Django 5.2.13 on 2026-04-27 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0091_rename_conteudo_ca_idioma__93e418_idx_conteudo_ca_idioma__c6a875_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariopublicacao',
            options={'ordering': ['criado_em'], 'verbose_name': 'Comentário da publicação', 'verbose_name_plural': 'Comentários das publicações'},
        ),
        migrations.AddField(
            model_name='comentariopublicacao',
            name='comentario_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='conteudo.comentariopublicacao', verbose_name='Comentário pai'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='oauth_google_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google client ID'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='oauth_google_client_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google client secret'),
        ),
        migrations.AddField(
            model_name='quizperguntapublicacao',
            name='exigir_todas_corretas',
            field=models.BooleanField(default=True, help_text='Se houver mais de uma opção correta, esta regra define se o usuário precisa marcar todas as corretas para acertar.', verbose_name='Exigir todas as respostas corretas'),
        ),
        migrations.AlterField(
            model_name='identidadeexternacomentario',
            name='provider',
            field=models.CharField(choices=[('orcid', 'ORCID'), ('github', 'GitHub'), ('google', 'Google'), ('gitlab', 'GitLab')], db_index=True, max_length=20, verbose_name='Provedor'),
        ),
        migrations.CreateModel(
            name='DuvidaQuizPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Pergunta')),
                ('permitir_publicacao_comentarios', models.BooleanField(default=False, verbose_name='Permitir publicar pergunta e resposta nos comentários')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('respondida', 'Respondida'), ('arquivada', 'Arquivada')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('publicado_como_comentario_em', models.DateTimeField(blank=True, null=True, verbose_name='Publicado nos comentários em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('comentario_pergunta_publicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conteudo.comentariopublicacao', verbose_name='Comentário da pergunta publicado')),
                ('comentario_resposta_publicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conteudo.comentariopublicacao', verbose_name='Comentário da resposta publicado')),
                ('pergunta_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duvidas_recebidas', to='conteudo.quizperguntapublicacao', verbose_name='Pergunta do quiz')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duvidas_quiz', to='conteudo.publicacaopage', verbose_name='Publicação')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duvidas_quiz', to='conteudo.usuariocomentario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Dúvida do quiz',
                'verbose_name_plural': 'Dúvidas do quiz',
                'ordering': ['-criado_em'],
            },
        ),
    ]
