# Generated by Django 5.2.13 on 2026-04-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0092_alter_comentariopublicacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='oauth_codeberg_base_url',
            field=models.URLField(blank=True, default='https://codeberg.org', help_text='Use a URL do Codeberg público ou de uma instância Forgejo compatível.', verbose_name='Codeberg base URL'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='oauth_codeberg_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Codeberg client ID'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='oauth_codeberg_client_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Codeberg client secret'),
        ),
        migrations.AlterField(
            model_name='identidadeexternacomentario',
            name='provider',
            field=models.CharField(choices=[('orcid', 'ORCID'), ('github', 'GitHub'), ('google', 'Google'), ('codeberg', 'Codeberg'), ('gitlab', 'GitLab')], db_index=True, max_length=20, verbose_name='Provedor'),
        ),
    ]
