# Generated by Django 5.2.13 on 2026-04-30 02:58

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0096_notarodapepublicacaoidiomamanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaQuizCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traducoes', models.JSONField(blank=True, default=dict, editable=False)),
                ('pergunta', models.CharField(max_length=500, verbose_name='Pergunta')),
                ('explicacao', models.TextField(blank=True, verbose_name='Explicação (opcional)')),
                ('exigir_todas_corretas', models.BooleanField(default=True, help_text='Se houver mais de uma opção correta, esta regra define se o usuário precisa marcar todas as corretas para acertar.', verbose_name='Exigir todas as respostas corretas')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pergunta reutilizável do quiz',
                'verbose_name_plural': 'Perguntas reutilizáveis do quiz',
                'ordering': ['-atualizado_em', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TagPerguntaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('traducoes', models.JSONField(blank=True, default=dict, editable=False)),
            ],
            options={
                'verbose_name': 'Tag de pergunta do quiz',
                'verbose_name_plural': 'Tags de perguntas do quiz',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemaPerguntaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traducoes', models.JSONField(blank=True, default=dict, editable=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tema de pergunta do quiz',
                'verbose_name_plural': 'Temas de perguntas do quiz',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='duvidaquizpublicacao',
            name='pergunta_catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duvidas_recebidas', to='conteudo.perguntaquizcatalogo', verbose_name='Pergunta reutilizável do quiz'),
        ),
        migrations.CreateModel(
            name='QuizOpcaoPerguntaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('traducoes', models.JSONField(blank=True, default=dict, editable=False)),
                ('texto', models.CharField(max_length=400, verbose_name='Texto da opção')),
                ('correta', models.BooleanField(default=False, verbose_name='Correta')),
                ('pergunta', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='conteudo.perguntaquizcatalogo')),
            ],
            options={
                'verbose_name': 'Opção da pergunta reutilizável',
                'verbose_name_plural': 'Opções da pergunta reutilizável',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaQuizCatalogoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='conteudo.perguntaquizcatalogo')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='conteudo.tagperguntaquiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='perguntaquizcatalogo',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='Use tags já cadastradas para facilitar o reuso e a filtragem.', through='conteudo.PerguntaQuizCatalogoTag', to='conteudo.TagPerguntaQuiz', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='perguntaquizcatalogo',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_quiz', to='conteudo.temaperguntaquiz', verbose_name='Tema'),
        ),
        migrations.CreateModel(
            name='PublicacaoPerguntaQuizCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_vinculadas', to='conteudo.perguntaquizcatalogo', verbose_name='Pergunta do catálogo')),
                ('publicacao', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_perguntas_reutilizaveis', to='conteudo.publicacaopage')),
            ],
            options={
                'verbose_name': 'Pergunta reutilizável vinculada à publicação',
                'verbose_name_plural': 'Perguntas reutilizáveis vinculadas à publicação',
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('publicacao', 'pergunta'), name='unique_publicacao_pergunta_quiz_catalogo')],
            },
        ),
    ]
