# Generated by Codex on 2026-04-30

import uuid
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0097_perguntaquizcatalogo_tagperguntaquiz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAcessoCodigo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Token")),
                ("codigo", models.CharField(db_index=True, max_length=6, verbose_name="Código")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("expira_em", models.DateTimeField(verbose_name="Expira em")),
                ("usado_em", models.DateTimeField(blank=True, null=True, verbose_name="Usado em")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("pagina", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="conteudo.quizestudopage", verbose_name="Página de quiz")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="conteudo.usuariocomentario", verbose_name="Usuário")),
            ],
            options={
                "verbose_name": "Código de acesso do quiz",
                "verbose_name_plural": "Códigos de acesso do quiz",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="QuizSessaoUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("respondidas", models.PositiveIntegerField(default=0, verbose_name="Respondidas")),
                ("corretas", models.PositiveIntegerField(default=0, verbose_name="Corretas")),
                ("erradas", models.PositiveIntegerField(default=0, verbose_name="Erradas")),
                ("puladas", models.PositiveIntegerField(default=0, verbose_name="Puladas")),
                ("consideradas", models.PositiveIntegerField(default=0, verbose_name="Consideradas")),
                ("media_percentual", models.PositiveIntegerField(default=0, verbose_name="Média da sessão")),
                ("detalhes", models.JSONField(blank=True, default=dict, verbose_name="Detalhes da sessão")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("finalizado_em", models.DateTimeField(auto_now_add=True, verbose_name="Finalizado em")),
                ("pagina", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sessoes_usuario", to="conteudo.quizestudopage", verbose_name="Página de quiz")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quiz_sessoes", to="conteudo.usuariocomentario", verbose_name="Usuário")),
            ],
            options={
                "verbose_name": "Sessão de quiz do usuário",
                "verbose_name_plural": "Sessões de quiz dos usuários",
                "ordering": ["-finalizado_em", "-criado_em"],
            },
        ),
        migrations.AddField(
            model_name="quizperguntapublicacao",
            name="tags",
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text="Use tags próprias do quiz para organizar esta pergunta.", to="conteudo.tagperguntaquiz", verbose_name="Tags"),
        ),
        migrations.AddField(
            model_name="quizperguntapublicacao",
            name="tema",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="perguntas_publicacao_quiz", to="conteudo.temaperguntaquiz", verbose_name="Tema"),
        ),
    ]
