# Generated by Django 5.2.13 on 2026-05-07 19:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteudo", "0102_remover_taxonomia_legada_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perguntaquizcatalogo",
            name="categoria_editorial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perguntas_quiz_editoriais",
                to="conteudo.categoria",
                verbose_name="Categoria editorial",
            ),
        ),
        migrations.AlterField(
            model_name="perguntaquizcatalogo",
            name="tags_editoriais",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Use as mesmas tags editoriais disponíveis nas publicações.",
                to="conteudo.tagpublicacao",
                verbose_name="Tags editoriais",
            ),
        ),
    ]
