# Generated by Django 5.2.13 on 2026-05-22 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0104_alinhar_paleta_padrao_com_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizopcaoperguntapublicacao',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='quizperguntapublicacao',
            name='publicacao',
        ),
        migrations.RemoveField(
            model_name='duvidaquizpublicacao',
            name='pergunta_quiz',
        ),
        migrations.RemoveField(
            model_name='quizrespostausuario',
            name='pergunta_publicacao',
        ),
        migrations.AddField(
            model_name='perguntaquizcatalogo',
            name='origem',
            field=models.CharField(choices=[('catalogo', 'Criada no catálogo'), ('publicacao', 'Criada a partir de publicação')], db_index=True, default='catalogo', max_length=20, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='perguntaquizcatalogo',
            name='publicacao_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas_quiz_catalogo_origem', to='conteudo.publicacaopage', verbose_name='Publicação de origem'),
        ),
        migrations.DeleteModel(
            name='QuizOpcaoPerguntaPublicacao',
        ),
        migrations.DeleteModel(
            name='QuizPerguntaPublicacao',
        ),
    ]
