# Generated by Django 5.2.13 on 2026-05-22 17:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0106_remove_perguntaquizcatalogo_origem_and_publicacao_origem'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE conteudo_quizrespostausuario "
                        "DROP CONSTRAINT IF EXISTS unique_quiz_resposta_usuario_pergunta_publicacao"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='quizrespostausuario',
                    name='unique_quiz_resposta_usuario_pergunta_publicacao',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='comentarioacessocodigo',
            name='fluxo',
            field=models.CharField(choices=[('login', 'Entrar'), ('cadastro', 'Cadastro')], db_index=True, max_length=20, verbose_name='Fluxo'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='google_search_console_verification',
            field=models.CharField(blank=True, help_text='Conteúdo do meta tag `google-site-verification` (somente o valor).', max_length=255, verbose_name='Verificação do Google Search Console'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_exibir',
            field=models.BooleanField(default=True, verbose_name='Exibir item Início no menu'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_imagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem/logo do Início no menu'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_imagem_claro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem/logo do Início (tema claro)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_imagem_escuro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem/logo do Início (tema escuro)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_imagem_mobile_claro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem/logo do Início no mobile (tema claro)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_imagem_mobile_escuro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem/logo do Início no mobile (tema escuro)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_logo_altura_desktop_px',
            field=models.PositiveSmallIntegerField(default=72, help_text='Altura máxima em pixels para desktop. Intervalo: 24 a 80.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(80)], verbose_name='Altura do botão/logo do Início no desktop (px)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_logo_altura_mobile_px',
            field=models.PositiveSmallIntegerField(default=50, help_text='Altura máxima em pixels para mobile. Intervalo: 24 a 80.', validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(80)], verbose_name='Altura do botão/logo do Início no mobile (px)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_logo_proporcao',
            field=models.CharField(choices=[('auto', 'Manter proporção original da imagem'), ('1:1', '1:1'), ('3:2', '3:2'), ('4:3', '4:3'), ('5:1', '5:1'), ('16:9', '16:9'), ('21:9', '21:9'), ('12:5', '12:5')], default='auto', help_text='Defina uma proporção fixa ou mantenha a original do arquivo enviado.', max_length=20, verbose_name='Proporção do botão/logo do Início'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_primeiro_fixo',
            field=models.BooleanField(default=True, help_text='Desative para ordenar o Início manualmente via Menu principal.', verbose_name='Fixar Início sempre no primeiro item'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='menu_home_rotulo',
            field=models.CharField(blank=True, default='Início', max_length=120, verbose_name='Rótulo do Início no menu'),
        ),
        migrations.AlterField(
            model_name='menuprincipalgrupo',
            name='atalho',
            field=models.CharField(blank=True, choices=[('home', 'Início'), ('categorias', 'Categorias'), ('tags', 'Tags'), ('autores', 'Autores'), ('busca', 'Busca'), ('destaques', 'Âncora: Destaques'), ('ultimas', 'Âncora: Últimas publicações'), ('contato', 'Contato'), ('newsletter', 'Newsletter'), ('indexador', 'Indexador')], max_length=30, verbose_name='Atalho do site'),
        ),
        migrations.AlterField(
            model_name='menuprincipalsubitem',
            name='atalho',
            field=models.CharField(blank=True, choices=[('home', 'Início'), ('categorias', 'Categorias'), ('tags', 'Tags'), ('autores', 'Autores'), ('busca', 'Busca'), ('destaques', 'Âncora: Destaques'), ('ultimas', 'Âncora: Últimas publicações'), ('contato', 'Contato'), ('newsletter', 'Newsletter'), ('indexador', 'Indexador')], max_length=30, verbose_name='Atalho do site'),
        ),
        migrations.AlterField(
            model_name='rodapelink',
            name='atalho',
            field=models.CharField(blank=True, choices=[('home', 'Início'), ('categorias', 'Categorias'), ('tags', 'Tags'), ('autores', 'Autores'), ('busca', 'Busca'), ('destaques', 'Âncora: Destaques'), ('ultimas', 'Âncora: Últimas publicações'), ('contato', 'Contato'), ('newsletter', 'Newsletter'), ('indexador', 'Indexador')], max_length=30, verbose_name='Atalho do site'),
        ),
    ]
