# Generated by Django 5.2.13 on 2026-05-25 20:13

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0107_remove_quizrespostausuario_unique_quiz_resposta_usuario_pergunta_publicacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conviteusuario',
            name='tipo_perfil',
        ),
        migrations.RemoveField(
            model_name='publicacaopage',
            name='aguardando_aprovacao_admin',
        ),
        migrations.RemoveField(
            model_name='publicacaopage',
            name='aprovado_em',
        ),
        migrations.RemoveField(
            model_name='publicacaopage',
            name='aprovado_por',
        ),
        migrations.RemoveField(
            model_name='publicacaopage',
            name='enviado_aprovacao_em',
        ),
        migrations.AddField(
            model_name='categoria',
            name='aprovacao_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=20, verbose_name='Status editorial'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='assinatura_email_padrao',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Assinatura padrão dos e-mails operacionais'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='doacoes_ativas',
            field=models.BooleanField(default=False, verbose_name='Ativar apoios/doações no site'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='doacoes_descricao',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descrição da página de apoio'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='doacoes_detalhes',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Outros meios de apoio/doação'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='doacoes_exibir_em_publicacoes',
            field=models.BooleanField(default=False, verbose_name='Exibir bloco de apoio no fim das publicações'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='doacoes_exibir_no_rodape',
            field=models.BooleanField(default=True, verbose_name='Exibir link de apoio no rodapé'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='doacoes_link_externo',
            field=models.URLField(blank=True, verbose_name='Link externo principal de apoio'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='doacoes_pix_chave',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chave Pix'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='doacoes_rotulo',
            field=models.CharField(blank=True, default='Apoie', max_length=120, verbose_name='Rótulo do botão/link de apoio'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='doacoes_titulo',
            field=models.CharField(default='Apoie o projeto', max_length=255, verbose_name='Título da página de apoio'),
        ),
        migrations.AddField(
            model_name='conviteusuario',
            name='papel_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AddField(
            model_name='conviteusuario',
            name='papel_autor',
            field=models.BooleanField(default=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='conviteusuario',
            name='papel_operacao',
            field=models.BooleanField(default=False, verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='conviteusuario',
            name='papel_revisor',
            field=models.BooleanField(default=False, verbose_name='Revisor'),
        ),
        migrations.AddField(
            model_name='conviteusuario',
            name='pode_publicar_direto',
            field=models.BooleanField(default=False, verbose_name='Pode publicar direto'),
        ),
        migrations.AddField(
            model_name='perguntaquizcatalogo',
            name='aprovacao_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=20, verbose_name='Status editorial'),
        ),
        migrations.AddField(
            model_name='perguntaquizcatalogo',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='perguntaquizcatalogo',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='perguntaquizcatalogo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publicado em'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='publicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publicado por'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='reabertura_solicitada',
            field=models.BooleanField(default=False, verbose_name='Reabertura solicitada'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='reabertura_solicitada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reabertura solicitada em'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='reabertura_solicitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reabertura solicitada por'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='revisao_solicitada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revisão solicitada em'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='revisao_solicitada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisão solicitada por'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='status_editorial',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em revisão'), ('ajustes_solicitados', 'Ajustes solicitados'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('publicado', 'Publicado')], db_index=True, default='rascunho', max_length=32, verbose_name='Status editorial'),
        ),
        migrations.AddField(
            model_name='tagpublicacao',
            name='aprovacao_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=20, verbose_name='Status editorial'),
        ),
        migrations.AddField(
            model_name='tagpublicacao',
            name='aprovado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em'),
        ),
        migrations.AddField(
            model_name='tagpublicacao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por'),
        ),
        migrations.AddField(
            model_name='tagpublicacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.CreateModel(
            name='SolicitacaoMudancaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('remover_admin', 'Remover papel de admin'), ('desativar_usuario', 'Desativar usuário admin')], max_length=30, verbose_name='Tipo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('usuario_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_mudanca_admin', to=settings.AUTH_USER_MODEL, verbose_name='Usuário alvo')),
            ],
            options={
                'verbose_name': 'Solicitação de mudança sensível de admin',
                'verbose_name_plural': 'Solicitações de mudanças sensíveis de admin',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioPainelPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_publicar_direto', models.BooleanField(default=False, verbose_name='Pode publicar direto')),
                ('assinatura_email', wagtail.fields.RichTextField(blank=True, verbose_name='Assinatura de e-mail do usuário')),
                ('email_monitoramento_respostas', models.EmailField(blank=True, max_length=254, verbose_name='E-mail para monitorar respostas enviadas pelo usuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='painel_perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil do usuário do painel',
                'verbose_name_plural': 'Perfis dos usuários do painel',
            },
        ),
        migrations.CreateModel(
            name='PublicacaoRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_atribuicao', models.CharField(choices=[('manual', 'Manual'), ('aleatoria', 'Aleatória')], default='manual', max_length=20, verbose_name='Modo de atribuição')),
                ('decisao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovar', 'Aprovar'), ('ajustes', 'Solicitar ajustes'), ('rejeitar', 'Rejeitar')], db_index=True, default='pendente', max_length=20, verbose_name='Decisão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atribuido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído por')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='conteudo.publicacaopage')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Revisor')),
            ],
            options={
                'verbose_name': 'Revisão de publicação',
                'verbose_name_plural': 'Revisões de publicações',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('publicacao', 'revisor'), name='unique_publicacao_revisor')],
            },
        ),
    ]
