# Generated by Django 5.2.13 on 2026-05-29 14:52

import django.db.models.deletion
import conteudo.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0113_estatisticatemposite'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaPendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('documento', 'Documento PDF')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('arquivo', models.FileField(storage=conteudo.storage.PrivatePendingMediaStorage(), upload_to='arquivos/', verbose_name='Arquivo sanitizado em quarentena')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome original')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='Content-Type')),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Tamanho em bytes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('revisado_em', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Mídia pendente',
                'verbose_name_plural': 'Mídias pendentes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='midiapendente',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='midiapendente',
            name='documento_aprovado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Documento aprovado'),
        ),
        migrations.AddField(
            model_name='midiapendente',
            name='imagem_aprovada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem aprovada'),
        ),
        migrations.AddField(
            model_name='midiapendente',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
    ]
