# Generated by Django 5.2.13 on 2026-05-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0114_midiapendente_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagempublicacao',
            name='midia_pendente',
            field=models.ForeignKey(blank=True, help_text='Use quando a imagem ainda depende de aprovação. Após aprovada, a imagem final será vinculada automaticamente.', limit_choices_to={'tipo': 'imagem'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos_em_publicacoes', to='conteudo.midiapendente', verbose_name='Mídia pendente'),
        ),
        migrations.AlterField(
            model_name='imagempublicacao',
            name='imagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagem'),
        ),
    ]
