# Generated by Django 5.2.14 on 2026-05-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0115_imagempublicacao_midia_pendente_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publicacaorevisao',
            name='unique_publicacao_revisor',
        ),
    ]
