# Generated by Django 5.2.14 on 2026-05-29 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0116_revisao_publicacao_historico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoComentarioRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trecho', models.TextField(blank=True, verbose_name='Trecho ou referência')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('resolvido', models.BooleanField(db_index=True, default=False, verbose_name='Resolvido')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_revisao', to='conteudo.publicacaopage')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
                ('revisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='conteudo.publicacaorevisao', verbose_name='Revisão')),
            ],
            options={
                'verbose_name': 'Comentário de revisão',
                'verbose_name_plural': 'Comentários de revisão',
                'ordering': ['resolvido', '-criado_em'],
            },
        ),
    ]
