# Generated by Django 5.2.14 on 2026-06-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0118_comentario_revisao_ancoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagempublicacao',
            name='marcadores_adicionais',
            field=models.TextField(blank=True, help_text='Opcional. Use quando a mesma imagem aparecer mais de uma vez com marcadores diferentes. Separe por vírgula, ponto e vírgula ou linha.', verbose_name='Marcadores adicionais'),
        ),
        migrations.AddField(
            model_name='midiaincorporadapublicacao',
            name='marcadores_adicionais',
            field=models.TextField(blank=True, help_text='Opcional. Use quando o mesmo vídeo aparecer mais de uma vez com marcadores diferentes. Separe por vírgula, ponto e vírgula ou linha.', verbose_name='Marcadores adicionais'),
        ),
        migrations.AddField(
            model_name='notarodapepublicacao',
            name='marcadores_adicionais',
            field=models.TextField(blank=True, help_text='Opcional. Use quando a mesma nota aparecer mais de uma vez com marcadores diferentes. Separe por vírgula, ponto e vírgula ou linha.', verbose_name='Marcadores adicionais'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='ordenacao_creditos',
            field=models.CharField(choices=[('aparicao', 'Ordem de aparição no texto'), ('marcador', 'Marcador'), ('alfabetica', 'Ordem alfabética')], default='aparicao', max_length=20, verbose_name='Ordenação dos créditos de mídia'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='ordenacao_notas_rodape',
            field=models.CharField(choices=[('aparicao', 'Ordem de aparição no texto'), ('marcador', 'Marcador'), ('alfabetica', 'Ordem alfabética')], default='aparicao', max_length=20, verbose_name='Ordenação das notas de rodapé'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='ordenacao_referencias',
            field=models.CharField(choices=[('aparicao', 'Ordem de aparição no texto'), ('marcador', 'Marcador'), ('alfabetica', 'Ordem alfabética')], default='aparicao', max_length=20, verbose_name='Ordenação das referências'),
        ),
        migrations.AddField(
            model_name='referenciapublicacao',
            name='marcadores_adicionais',
            field=models.TextField(blank=True, help_text='Opcional. Use quando a mesma referência aparecer mais de uma vez com marcadores diferentes. Separe por vírgula, ponto e vírgula ou linha.', verbose_name='Marcadores adicionais'),
        ),
    ]
