# Generated by Django 5.2.14 on 2026-06-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0119_complementos_multiplos_marcadores_ordenacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiapendente',
            name='substituicao_token',
            field=models.CharField(blank=True, db_index=True, help_text='Uso interno para reinserir documento aprovado em publicações.', max_length=80, verbose_name='Token de substituição'),
        ),
        migrations.AddField(
            model_name='midiapendente',
            name='texto_link',
            field=models.CharField(blank=True, help_text='Texto usado ao reinserir documento aprovado na publicação.', max_length=255, verbose_name='Texto do link'),
        ),
        migrations.AddField(
            model_name='publicacaopage',
            name='imagem_capa_pendente',
            field=models.ForeignKey(blank=True, help_text='Preenchido automaticamente quando uma capa enviada por autor aguarda aprovação.', limit_choices_to={'tipo': 'imagem'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas_em_publicacoes', to='conteudo.midiapendente', verbose_name='Imagem de capa pendente'),
        ),
    ]
