# Generated by Django 5.2.14 on 2026-06-01 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0121_publicacao_atualizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiaincorporadapublicacao',
            name='midia_pendente',
            field=models.ForeignKey(blank=True, help_text='Use para vídeo local enviado em Mídias pendentes. Se ainda estiver pendente, o site exibe um aviso até a aprovação.', limit_choices_to={'tipo': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_em_publicacoes', to='conteudo.midiapendente', verbose_name='Vídeo local'),
        ),
        migrations.AddField(
            model_name='midiaincorporadapublicacao',
            name='origem_video',
            field=models.CharField(choices=[('externa', 'Vídeo externo'), ('local', 'Vídeo local aprovado ou pendente')], default='externa', max_length=20, verbose_name='Origem do vídeo'),
        ),
        migrations.AddField(
            model_name='midiapendente',
            name='video_aprovado',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='Vídeo aprovado'),
        ),
        migrations.AlterField(
            model_name='midiaincorporadapublicacao',
            name='url',
            field=models.URLField(blank=True, help_text='Use uma URL incorporável, como YouTube ou Vimeo.', verbose_name='URL do vídeo'),
        ),
        migrations.AlterField(
            model_name='midiapendente',
            name='tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('documento', 'Documento PDF'), ('video', 'Vídeo')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
    ]
