# Generated by Django 5.2.14 on 2026-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0130_remove_panel_managed_backup_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupexecucao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_execucao', 'Em execução'), ('concluido', 'Concluído'), ('falhou', 'Falhou')], db_index=True, max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='backupexecucao',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Manual'), ('agendado', 'Agendado'), ('painel', 'Painel')], default='manual', max_length=20, verbose_name='Tipo'),
        ),
    ]
