# Generated by Django 5.2.15 on 2026-06-04 15:21

import conteudo.models
import conteudo.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudo', '0133_remover_traducao_automatica_busca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='submissoes_exigir_orcid',
            field=models.BooleanField(default=False, help_text='Quando ativo, o cadastro público precisa ter ORCID válido para enviar submissões.', verbose_name='Exigir ORCID nas submissões públicas'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='submissoes_limite_pdf_mb',
            field=models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Limite do PDF de submissão (MB)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='submissoes_publicas_ativas',
            field=models.BooleanField(default=False, help_text='Permite que usuários cadastrados no site público enviem textos para triagem editorial.', verbose_name='Ativar submissões públicas'),
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem'),
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='sinalizado_conteudo',
            field=models.BooleanField(default=False, help_text='Marcado automaticamente quando a mensagem contém padrões suspeitos.', verbose_name='Sinalizado por conteúdo'),
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, verbose_name='User agent'),
        ),
        migrations.CreateModel(
            name='SubmissaoPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem para a equipe')),
                ('arquivo_pdf', models.FileField(storage=conteudo.storage.PrivateSubmissionStorage(), upload_to=conteudo.models.submissao_publica_upload_to, verbose_name='PDF sanitizado')),
                ('arquivo_nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome original')),
                ('arquivo_tamanho', models.PositiveIntegerField(default=0, verbose_name='Tamanho do arquivo')),
                ('arquivo_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256 do arquivo')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('em_triagem', 'Em triagem'), ('ajustes_solicitados', 'Ajustes solicitados'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada'), ('convertida', 'Convertida em publicação')], db_index=True, default='recebida', max_length=32, verbose_name='Status')),
                ('ficha_nome_completo', models.CharField(blank=True, max_length=255, verbose_name='Nome completo para autoria')),
                ('ficha_nome_exibicao', models.CharField(blank=True, max_length=255, verbose_name='Nome de exibição')),
                ('ficha_mini_bio', models.TextField(blank=True, verbose_name='Mini bio')),
                ('ficha_instagram', models.CharField(blank=True, max_length=255, verbose_name='Instagram')),
                ('ficha_mastodon', models.URLField(blank=True, verbose_name='Mastodon')),
                ('ficha_lattes_url', models.URLField(blank=True, verbose_name='Link do Lattes')),
                ('texto_final', models.TextField(blank=True, verbose_name='Texto final enviado pelo autor')),
                ('token_acesso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de acesso público')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('decidido_em', models.DateTimeField(blank=True, null=True, verbose_name='Decidido em')),
                ('observacao_admin', models.TextField(blank=True, verbose_name='Observação administrativa')),
                ('autor_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissoes_publicas', to='conteudo.autor', verbose_name='Autor vinculado')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('publicacao_criada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissoes_origem', to='conteudo.publicacaopage', verbose_name='Publicação criada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissoes_publicas', to='conteudo.usuariocomentario', verbose_name='Usuário público')),
            ],
            options={
                'verbose_name': 'Submissão pública',
                'verbose_name_plural': 'Submissões públicas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
