from django.urls import path
from .feeds import PublicacoesRSSFeed

from .views import (
    autor_detalhe,
    autores_index,
    busca_publicacoes,
    categoria_detalhe,
    categorias_index,
    convite_aceitar,
    email_click_track,
    email_open_track,
    estatistica_tempo_site,
    contato_form,
    newsletter_cancelar,
    newsletter_confirmar,
    newsletter_form,
    newsletter_solicitar_cancelamento,
    newsletter_solicitar_privacidade,
    newsletter_confirmar_exclusao_privacidade,
    newsletter_cancelar_exclusao_privacidade,
    pagina_apoio,
    indexador_exportar_csv,
    indexador_registro_detalhe,
    publicacoes_por_tag,
    publicacao_pdf,
    robots_txt,
    tags_index,
    comentario_login_solicitar_codigo,
    comentario_cadastro_solicitar_codigo,
    comentario_confirmar_codigo,
    comentario_enviar,
    comentario_logout,
    comentario_oauth_callback,
    comentario_oauth_concluir,
    comentario_oauth_iniciar,
    comentario_solicitar_verificacao,
    comentario_confirmar_verificacao,
    duvida_quiz_enviar,
    quiz_cadastro_solicitar_codigo,
    quiz_confirmar_codigo,
    quiz_login_solicitar_codigo,
    quiz_logout,
    quiz_oauth_callback,
    quiz_oauth_concluir,
    quiz_oauth_iniciar,
    quiz_resposta_salvar,
    quiz_sessao_salvar,
    quiz_tag_detalhe,
    quiz_tema_detalhe,
    avaliacao_publicacao_enviar,
    username_disponivel,
    submissao_publica,
    submissao_publica_completar,
)

urlpatterns = [
    path("robots.txt", robots_txt, name="robots_txt"),
    path("estatisticas/tempo/", estatistica_tempo_site, name="estatistica_tempo_site"),
    path("acesso/username-disponivel/", username_disponivel, name="username_disponivel"),
    path("submissoes/", submissao_publica, name="submissao_publica"),
    path(
        "submissoes/completar/<uuid:token>/",
        submissao_publica_completar,
        name="submissao_publica_completar",
    ),
    path(
        "publicacao/<int:page_id>/comentarios/login/solicitar/",
        comentario_login_solicitar_codigo,
        name="comentario_login_solicitar_codigo",
    ),
    path(
        "publicacao/<int:page_id>/comentarios/cadastro/solicitar/",
        comentario_cadastro_solicitar_codigo,
        name="comentario_cadastro_solicitar_codigo",
    ),
    path(
        "publicacao/<int:page_id>/comentarios/confirmar-codigo/",
        comentario_confirmar_codigo,
        name="comentario_confirmar_codigo",
    ),
    path(
        "publicacao/<int:page_id>/comentarios/enviar/",
        comentario_enviar,
        name="comentario_enviar",
    ),
    path(
        "publicacao/<int:page_id>/quiz/duvida/enviar/",
        duvida_quiz_enviar,
        name="duvida_quiz_enviar",
    ),
    path(
        "quiz/<int:page_id>/login/solicitar/",
        quiz_login_solicitar_codigo,
        name="quiz_login_solicitar_codigo",
    ),
    path(
        "quiz/<int:page_id>/cadastro/solicitar/",
        quiz_cadastro_solicitar_codigo,
        name="quiz_cadastro_solicitar_codigo",
    ),
    path(
        "quiz/<int:page_id>/confirmar-codigo/",
        quiz_confirmar_codigo,
        name="quiz_confirmar_codigo",
    ),
    path(
        "quiz/<int:page_id>/logout/",
        quiz_logout,
        name="quiz_logout",
    ),
    path(
        "quiz/<int:page_id>/oauth/<str:provider>/iniciar/",
        quiz_oauth_iniciar,
        name="quiz_oauth_iniciar",
    ),
    path(
        "quiz/oauth/<str:provider>/callback/",
        quiz_oauth_callback,
        name="quiz_oauth_callback",
    ),
    path(
        "quiz/<int:page_id>/oauth/concluir/",
        quiz_oauth_concluir,
        name="quiz_oauth_concluir",
    ),
    path(
        "quiz/<int:page_id>/sessao/salvar/",
        quiz_sessao_salvar,
        name="quiz_sessao_salvar",
    ),
    path(
        "publicacao/<int:page_id>/quiz/resposta/salvar/",
        quiz_resposta_salvar,
        name="quiz_resposta_salvar",
    ),
    path(
        "quiz/<int:page_id>/tema/<str:slug>/",
        quiz_tema_detalhe,
        name="quiz_tema_detalhe",
    ),
    path(
        "quiz/<int:page_id>/tag/<str:slug>/",
        quiz_tag_detalhe,
        name="quiz_tag_detalhe",
    ),
    path(
        "publicacao/<int:page_id>/comentarios/logout/",
        comentario_logout,
        name="comentario_logout",
    ),
    path(
        "publicacao/<int:page_id>/comentarios/oauth/<str:provider>/iniciar/",
        comentario_oauth_iniciar,
        name="comentario_oauth_iniciar",
    ),
    path(
        "comentarios/oauth/<str:provider>/callback/",
        comentario_oauth_callback,
        name="comentario_oauth_callback",
    ),
    path(
        "publicacao/<int:page_id>/comentarios/oauth/concluir/",
        comentario_oauth_concluir,
        name="comentario_oauth_concluir",
    ),
    path(
        "publicacao/<int:page_id>/avaliacao/enviar/",
        avaliacao_publicacao_enviar,
        name="avaliacao_publicacao_enviar",
    ),
    path(
        "publicacao/<int:page_id>/comentarios/solicitar/",
        comentario_solicitar_verificacao,
        name="comentario_solicitar_verificacao",
    ),
    path(
        "comentarios/confirmar/<uuid:token>/",
        comentario_confirmar_verificacao,
        name="comentario_confirmar_verificacao",
    ),
    path("email/track/open/<uuid:token>/", email_open_track, name="email_open_track"),
    path("email/track/click/<uuid:token>/", email_click_track, name="email_click_track"),
    path("rss.xml", PublicacoesRSSFeed(), name="rss_publicacoes"),
    path("feed/", PublicacoesRSSFeed(), name="feed_publicacoes"),
    path("convites/aceitar/<str:token>/", convite_aceitar, name="convite_aceitar"),
    path("contato/<slug:slug>/enviar/", contato_form, name="contato_form"),
    path("newsletter/<slug:slug>/inscrever/", newsletter_form, name="newsletter_form"),
    path("newsletter/<slug:slug>/solicitar-cancelamento/", newsletter_solicitar_cancelamento, name="newsletter_solicitar_cancelamento"),
    path("newsletter/<slug:slug>/confirmar/<str:token>/", newsletter_confirmar, name="newsletter_confirmar"),
    path("newsletter/<slug:slug>/cancelar/<str:token>/", newsletter_cancelar, name="newsletter_cancelar"),
    path(
        "newsletter/<slug:slug>/solicitar-privacidade/",
        newsletter_solicitar_privacidade,
        name="newsletter_solicitar_privacidade",
    ),
    path(
        "newsletter/<slug:slug>/confirmar-exclusao-privacidade/<str:token>/",
        newsletter_confirmar_exclusao_privacidade,
        name="newsletter_confirmar_exclusao_privacidade",
    ),
    path(
        "newsletter/<slug:slug>/cancelar-exclusao-privacidade/<str:token>/",
        newsletter_cancelar_exclusao_privacidade,
        name="newsletter_cancelar_exclusao_privacidade",
    ),
    path(
        "indexador/<slug:page_slug>/registro/<slug:registro_slug>/",
        indexador_registro_detalhe,
        name="indexador_registro_detalhe",
    ),
    path(
        "indexador/<slug:page_slug>/exportar/",
        indexador_exportar_csv,
        name="indexador_exportar_csv",
    ),
    path("busca/", busca_publicacoes, name="busca_publicacoes"),
    path(
        "publicacao/<int:page_id>/pdf/",
        publicacao_pdf,
        name="publicacao_pdf",
    ),
    path("categorias/", categorias_index, name="categorias_index"),
    path("categorias/<str:slug>/", categoria_detalhe, name="categoria_detalhe"),
    path("autores/", autores_index, name="autores_index"),
    path("autores/<slug:username>/", autor_detalhe, name="autor_detalhe"),
    path("apoio/", pagina_apoio, name="pagina_apoio"),
    path("tags/", tags_index, name="tags_index"),
    path("tags/<str:slug>/", publicacoes_por_tag, name="publicacoes_por_tag"),
]
